name: CI/CD — Build, Test & Deploy

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "main" ] # Only deploy the final image from main

env:
  DOCKER_IMAGE: ghcr.io/richinlearns/cookiegram-demo
  TAG: ${{ github.sha }}

jobs:
  # 1️⃣ Build & Test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven and Run Tests
        run: mvn -B clean install -DskipTests

      - name: Upload JAR artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports

  # 2️⃣ Docker Build & Push
  docker_deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
