name: CI/CD — Build, Test & Deploy

on:
  push:
    branches: [ "*" ]   # test on all branches
  pull_request:
    branches: [ "*" ]   # test on all PRs

env:
  DOCKER_IMAGE: ghcr.io/richinlearns/cookiegram-demo
  TAG: ${{ github.sha }}

jobs:
  # 1️⃣ Build & Test for every branch/PR
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven (skip tests if needed)
        run: mvn -B clean install -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

  # 2️⃣ Docker Build & Push only on main
  docker_deploy:
    needs: build
    if: github.ref == 'refs/heads/main'   # only trigger for main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
